# Generated by Django 3.1.1 on 2020-09-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='enc_string',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='input',
            name='key',
            field=models.CharField(max_length=100),
        ),
    ]
