# Generated by Django 3.1.1 on 2020-09-26 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0003_auto_20200925_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vertex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=100)),
                ('x_val', models.IntegerField()),
                ('y_val', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_one', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vertexone', to='graph.vertex')),
                ('v_two', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vertextwo', to='graph.vertex')),
            ],
        ),
    ]
